name: license_check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - "pubspec.yaml"
      - ".github/workflows/license_check.yaml"
      - "pubspec.lock"
  push:
    branches:
      - main
    paths:
      - "pubspec.yaml"
      - ".github/workflows/license_check.yaml"
      - "pubspec.lock"

jobs:
  license_check:
    uses: ./.github/workflow-templates/license_checker.yml
    with:
      flutter_version: "3.41.9"
      flutter_channel: "stable"
      skip_packages: "vector_math"
      allowed: "MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0"
